# Generated by Django 4.2.7 on 2023-11-17 15:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_django', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mapa',
            new_name='Map',
        ),
    ]
