# Generated by Django 4.2.7 on 2023-11-17 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0003_alter_map_map_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='map_image',
            field=models.SlugField(max_length=1000, unique=True),
        ),
    ]
