# Generated by Django 4.2.7 on 2023-11-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0005_alter_map_map_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='usuario',
        ),
    ]
