# Generated by Django 4.2.7 on 2023-12-01 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_django', '0006_remove_map_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=2000)),
            ],
        ),
    ]
